"""empty message

Revision ID: 51997cb9be51
Revises: 5389922292d7
Create Date: 2025-12-07 18:20:24.802415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51997cb9be51'
down_revision: Union[str, None] = '5389922292d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('preview_file_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabs', 'preview_file_key')
    # ### end Alembic commands ###
